// Code generated by zero-api. DO NOT EDIT.

package svc

import (
	"context"
)

type Session struct {
	Svc
	context.Context
	UserID  int64
	TraceID string
}

func (sess *Session)TraceId() string {
	return sess.TraceID
}

func (sess *Session)SpanId() string {
	return ""
}

func (sess *Session)Visit(fn func(key, val string) bool) {
	
}