// Code generated by zero-api. DO NOT EDIT.

package proto

import (
	"bytes"
	"fmt"
	"io"
	"net/textproto"
	"strconv"
	"strings"
)

type File struct {
	Filename    string
	Header      textproto.MIMEHeader
	Size        int64
	File        io.ReadCloser
	ContentType string
}

func (f *File) Read(p []byte) (n int, err error) {
	return f.File.Read(p)
}

func (f *File) Close() error {
	return f.File.Close()
}

func (f *File) FromBytes(data []byte, contentType string) {
	f.FromReader(bytes.NewReader(data), contentType)
}

func (f *File) FromReader(reader io.Reader, contentType string) {
	f.File = io.NopCloser(reader)
	f.ContentType = contentType
}

type ID int64

func (id ID) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf(`"%d"`, id)), nil
}

func (id *ID) UnmarshalJSON(data []byte) error {
	n, err := strconv.ParseInt(strings.Trim(string(data), `"`), 10, 64)
	*id = ID(n)
	return err
}

type UID uint64

func (id UID) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf(`"%d"`, id)), nil
}

func (id *UID) UnmarshalJSON(data []byte) error {
	n, err := strconv.ParseUint(strings.Trim(string(data), `"`), 10, 64)
	*id = UID(n)
	return err
}
