// Code generated by zero-api. DO NOT EDIT.

package proto

{{if .ContainsMultipartFile}}import "mime/multipart"{{else}}{{end}}
{{range .Types}}
{{.Documents}}
type {{.Name}} struct {
{{range .Fields}}	{{.Documents}}
	{{.Name}} {{.Type}} {{.Tag}}
{{end}}}
{{end}}